### ISSUE TITLE
Compat with PHP 8.x - "match"

### ISSUE THREAD

**Issue by Chrico** [Toobo/Hop#1]
I'm getting following error:

```
Parse error: syntax error, unexpected token "match", expecting "(" in /var/www/...../vendor/toobo/hop/src/comparison.php on line 65
```

Looks like the `match` shoulnd't be used as function name due https://www.php.net/manual/de/control-structures.match.php which was introduced in PHP 8.0.

**Comment by gmazzap** [comment]
Thank you.

Of course, I need to rename the funcrion, but that is a BC change. 

So I released [v2.0.0](https://github.com/Toobo/Hop/releases/tag/2.0.0) that is compatible with PHP 8.0+, and at the same time, I released v1.1.0 that fixes Composer requirements making sure v1 is not installed on PHP 8.
